### ISSUE TITLE
cardano-testnet seems to make assumptions about where it is run

### ISSUE THREAD

**Issue by locallycompact** [IntersectMBO/cardano-node#4194]
Hi, I discovered the `cardano-testnet` executable, I was hoping to run it against a derivation containing the config for a private testnet but apparently I can not run it at all through nix.

```
nix build .#cardano-testnet
./result/bin/cardano-testnet cardano
```

```
    ━━━ Exception (IOException) ━━━
    ../dist-newstyle/cache/plan.json: openBinaryFile: does not exist (No such file or directory)

    This failure can be reproduced by running:
    > recheck (Size 0) (Seed 14417734425994254147 11580250401777982633) <property>
```

Why is it trying to look for things in dist-newstyle?

**Comment by eyeinsky** [comment]
I've just run into this as well, @locallycompact did you ever managed to resolve or work around it?

**Comment by koslambrou** [comment]
I fixed it locally by making the following env variables for Nix:

```
export CARDANO_CLI=${config.hsPkgs.cardano-cli.components.exes.cardano-cli}/bin/cardano-cli${pkgs.stdenv.hostPlatform.extensions.executable}
export CARDANO_NODE=${config.hsPkgs.cardano-node.components.exes.cardano-node}/bin/cardano-node${pkgs.stdenv.hostPlatform.extensions.executable}
export CARDANO_NODE_SRC=${src}
```

**Comment by Jimbo4350** [comment]
Closing this. Please reopen if this is still relevant.

**Comment by gilligan** [comment]
I had the same issue outlined here where I get the error with opening `../dist-newstyle/cache/plan.json` *unless*  `CARDANO_CLI` and `CARDANO_NODE` are set.

Setting those solves the issue but this still seems like a workaround to an actual problem to me.

**Comment by smelc** [comment]
This issue has also been reported by @johnalotoski [here on Slack](https://input-output-rnd.slack.com/archives/G011N23CEAE/p1733534904274509?thread_ts=1715651721.493559&cid=G011N23CEAE).

**Comment by smelc** [comment]
This is still an issue (on 238b4c8b23e9f528dcc78ee08cb29c1b599c0518), reproducible as follows:

```
# While in cardano-node repository
cabal build cardano-testnet
cabal build cardano-node

export TMP_PATH=$(mktemp -d)

cp $(cabal list-bin cardano-testnet) $(cabal list-bin cardano-node) $TMP_PATH/.
cd $TMP_PATH
./cardano-testnet cardano --num-pool-nodes 3 --testnet-magic 42
... lots of output
    ━━━ Exception (ErrorCall) ━━━
    Could not find plan.json in the path: dist-newstyle/cache/plan.json
    CallStack (from HasCallStack):
      createSPOGenesisAndFiles, called at src/Testnet/Start/Cardano.hs:199:8 in cardano-testnet-10.0.0-inplace:Testnet.Start.Cardano
      cardanoTestnet, called at src/Testnet/Start/Cardano.hs:93:3 in cardano-testnet-10.0.0-inplace:Testnet.Start.Cardano
      cardanoTestnetDefault, called at src/Parsers/Run.hs:71:61 in cardano-testnet-10.0.0-inplace:Parsers.Run
  
    This failure can be reproduced by running:
    > recheckAt (Seed 9184080727122563869 11195688623784977365) "1:" <property>
```

**Comment by smelc** [comment]
We need to change `hedgehog-extras`'s `binDist` function which `error`s here: https://github.com/input-output-hk/hedgehog-extras/blob/a8120b84d1baa4b26c69668fc37f307ba9e942e1/src/Hedgehog/Extras/Test/Process.hs#L302 when 1/ the environment variable for searching the executable isn't defined and 2/ the `plan.json` file doesn't exist.

As a long-term solution, we should not `error` out in this function, but rather have the callers handle the different failures. As a short-term solution, we should have a better error message when we fail, indicating that the environment variable can be defined as a workaround. I'm going to do the short-term solution to see how much progress we get regarding running `cardano-testnet` locally.
